### ISSUE TITLE
Status CH by choosing a GuildID & Channel ID

### ISSUE THREAD

**Issue by x-Ghosts** [PetyXbron/minecraft-bot#10]
Hello ! 

I've tried to follow the Guide about an Auto-Message refreshing for the server status.

Well, at the Terminal, right before the Bot finishes booting up, I get this : (Resulting the failure of its bootup)
![Img1](https://user-images.githubusercontent.com/78695896/173212360-7006deb3-021f-4c83-a709-62e44c99bf1a.PNG)
![Img2](https://user-images.githubusercontent.com/78695896/173212361-7ed4b26e-d5cc-434c-953f-385ba74cb57e.PNG)

I hope I did not do any mistake regarding adding only The GuildID & Channel ID where it supposed at the end to show, after every interval timer the status of the server without typing the Status command.

**Comment by PetyXbron** [comment]
Hello, @x-Ghosts! Can you please send me your `config.js` file (without Discord bot token or your "sensitive" data)? I would check if you didn't do anything wrong.

- **Also please check if your bot does have full permission to send messages to your "test" channel.**

Obviously the message didn't generate/send and it can't get the ID from it, because it doesn't exist. If it still doesn't work, try to give the bot administrator permission to just try it again.

**Comment by x-Ghosts** [comment]
Hello @PetyXbron , 

The Bot has actually all the permissions needed, acting as an Admin, + bots applications.commands feature on. Moreover, it's full access on the channel to read & send the messages, to manage the channel too.


Here is the File : **I shared it via Mediafire, the link is below** : **https://www.mediafire.com/file/6nxd5bd0h7c16k6/config.js/file**

**Comment by x-Ghosts** [comment]
Hello, 

Any news about the issue, or, an issue from my side ? I hope I've done things as they should be done via the guide.

**Comment by PetyXbron** [comment]
Hello, I am a bit busy this week. I will try to check out all issues of this project this weekend. And I have in my plan to make some bug-fixing release/update with some new functions. I will let you know in a couple of days.

**Comment by PetyXbron** [comment]
@x-Ghosts can you **please invite me to your Discord server** to inspect it more closely? I couldn't find any mistake in your config.
Send me a friend request to [PetyXbron#7777](https://discord.c99.nl/widget/theme-3/411436203330502658.png)!
