### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Timong-craft** [PetyXbron/minecraft-bot#12]
So I wanna ask if you can make a version were the "server" part in the config can be set individually via slash commands and be stored in a .json or something like that so that the bot can be on multiple servers. Can you do that?

**Comment by Timong-craft** [comment]
I have my community server, my team server, an projekt server and a school server and I don't want a bot for every server, but it was only a request/suggestion

**Comment by PetyXbron** [comment]
I decided not to work on this as part of this project.

**Comment by Timong-craft** [comment]
Ok
