### ISSUE TITLE
TypeError: EmbedBuilder is not a constructor

### ISSUE THREAD

**Issue by magoxado** [PetyXbron/minecraft-bot#15]
Whats the problem?

pic: https://cdn.discordapp.com/attachments/996711256016834604/1012670894654619699/unknown.png

**Comment by PetyXbron** [comment]
> Whats the problem?
> 
> pic: https://cdn.discordapp.com/attachments/996711256016834604/1012670894654619699/unknown.png

Please run command `npm list` and send me the output.
Assumption: You have outdated discord.js library (v13 --> v14) because of new update

If I will recognize that you have outdated packages installed, I will send you command how to install the latest.

**Comment by chethanyadav456** [comment]
**Kindly check u r discord package is up to date (v14) 
`npm install discord.js@latest` or just install `npm install discord.js`**

If u r facing anying error then feel free to contant me on discord - **Raaz#2233**

**Comment by PetyXbron** [comment]
I predict that the author has corrected the error.
The fixes mentioned above should resolve the issue.
