### ISSUE TITLE
DiscordAPIError: Invalid Form Body

### ISSUE THREAD

**Issue by MG141** [PetyXbron/minecraft-bot#2]
I am facing some startup issues with the bot if I could get a help with fixing it.
![Screenshot_20220216_113205](https://user-images.githubusercontent.com/65613737/154246847-7fd065b8-77e3-426e-ae58-adc05bb656c8.jpg)

**Comment by PetyXbron** [comment]
Hello, I am sorry that you're facing this problem. This is the first issue of this project and I needed this feedback. Do you have defined **server.icon** in [config.js](https://github.com/PetyXbron/minecraft-bot/blob/main/config.js#L17)?
If I understand it well, you haven't defined the Server Icon URL link. Code should use your Discord server one, but I probably see an error in getting the icon URL of your Discord guild.

**Comment by MG141** [comment]
Indeed it was that. Thank you.

**Comment by PetyXbron** [comment]
This bug shouldn't happen again even without setting the server icon URL in [config.js](https://github.com/PetyXbron/minecraft-bot/blob/main/config.js#L17).
