### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by ReiRei6969** [PetyXbron/minecraft-bot#20]
Hello, so I have this problem/question. 
Is is required for bot to work to have open VSC 24/7? Because when I exit it, it doesn't update or react to any of the commands.

**Comment by PetyXbron** [comment]
Hello @ReiRei6969. **Yes, if you are hosting on your personal computer, like Windows, you need to have the program running the project open.**
I can recommend you use a simple Windows Command Prompt ("cmd") to run minecraft-bot, you don't need to have VSC opened.
 You can search for instructions on how to minimize Command Prompt to tray if you want to hide the window as much as possible.
 Also consider hosting on some server, if you don't want to have your personal computer turned on 24/7.

**Comment by ReiRei6969** [comment]
Oh, okay I understand. Thanks
