### ISSUE TITLE
Privileged intent provided is not enabled

### ISSUE THREAD

**Issue by Tomper6161** [PetyXbron/minecraft-bot#21]
how do i fix this ? https://i.imgur.com/ybY3YR0.png

**Comment by PetyXbron** [comment]
Hello @Tomper6161.
Luckily, I have an easy fix for you.
Just go to the Discord Developers page, select your app, and then the bot page. Eable server members and message content intent.
After enabling, restart the process. It should work.
If you are interested in faster support response, consider joining [this project Discord support server](https://discord.com/invite/PYTqqhWad2).

**Comment by Tomper6161** [comment]
thank you thank you another question, sorry.

How do i make it so on the online list the bot shows like how many players are online, and can i have it for example

It showing online people for 10 sec then after that it shows the ip of the server after that something else etc? thanks!

**Comment by PetyXbron** [comment]
If I understood correctly, you are describing the minecraft-bot function called statusCH.
Its basically automatically updated message in the specified interval, which shows the player list and basic server info (server connection info and number of online players) [[example screenshot here](https://camo.githubusercontent.com/74c3c90ca1871ac755bce017bf7d4eaaa7300e925673f543d661404ec263a295/68747470733a2f2f692e696d6775722e636f6d2f4c3667464b34512e706e67)]
To set up this feature, go to [`config.js` settings](https://github.com/PetyXbron/minecraft-bot/blob/12eb91b2494c40f8a91e14ccb24b23d126319b73/config.js#L26) and enable statusCH, by setting the value to `true`.  Now go down a little, to the [statusCH settings](https://github.com/PetyXbron/minecraft-bot/blob/12eb91b2494c40f8a91e14ccb24b23d126319b73/config.js#L45) and enter the interval of a message update and paste your channel ID. Also, check if you have entered the server ID into the `config.js` too.
_If the message is successfully sent after the process starts, it will save the message ID to the `json.sqlite` file. Delete the file, if you want to send a new message._

**Comment by Tomper6161** [comment]
💛 Bot status type in config was empty! Bot presence is now set to "online"
Hint: hit control+c anytime to enter REPL.
💚 Successfully sent status message to server!
/home/runner/minecraft-bot/events/ready.js:155
            db.set('statusCHMsgID', msg.id);
                                        ^

TypeError: Cannot read properties of undefined (reading 'id')
    at module.exports (/home/runner/minecraft-bot/events/ready.js:155:41)

Node.js v18.12.1
repl process died unexpectedly: exit status 1
 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
 
repl process died unexpectedly: 
 


shows this when i paste chancel id on statusch at config at chancelid " " 

also i dont really want it in a chancel id rather have it on the bot on the right side on the online list like this  see the pic
https://i.imgur.com/BAi2sVu.png

**Comment by PetyXbron** [comment]
The bot could not send the statusCH message. Check the bot's permissions or re-invite it with the official link in the console.
If you are interested in faster support response and deeper help, consider joining [this project Discord support server](https://discord.com/invite/PYTqqhWad2).

**Comment by PetyXbron** [comment]
@Tomper6161, your new issue is connected to reported issues https://github.com/PetyXbron/minecraft-bot/issues/3, https://github.com/PetyXbron/minecraft-bot/issues/19, and https://github.com/PetyXbron/minecraft-bot/issues/10. 
Use release [v1.7.0](https://github.com/PetyXbron/minecraft-bot/releases/tag/1.7.0) or newer to potentially fix the issue.
