### ISSUE TITLE
Replit: TOML error

### ISSUE THREAD

**Issue by BLKOFFICIAL** [PetyXbron/minecraft-bot#24]
unable to read .replit: unable to decode replit: toml: line 5 (last key hidden): incompatible types: TOML value has type string; destination has type slice ntx error: building nix env: problem reading replit file: unable to decode .replit: toml: line 5 (last key "hidden"): incompatible types: TOM L value has type string; destination has type slice

this Is the error message

**Comment by PetyXbron** [comment]
I am sorry, but this issue should have **not been created by this project** ([minecraft-bot](https://github.com/PetyXbron/minecraft-bot)). It is a [replit](https://replit.com/) error.
Try to contact [replit](https://replit.com/) support for help. I have found these links:
- [Replit Discord server](https://replit.com/discord)
- [Replit help website](https://replit.com/help)

**Comment by PetyXbron** [comment]
**This project does not currently 100% support [Replit](https://replit.com/)**. The user must set up [Replit](https://replit.com/) support by itself.
I do not unfortunately know [Replit](https://replit.com/) so much to set this compatibility.
