### ISSUE TITLE
es error

### ISSUE THREAD

**Issue by omenwebsite** [PetyXbron/minecraft-bot#5]
![image](https://user-images.githubusercontent.com/95492750/161770304-741f98c8-6ac4-45cb-a24b-7d3a6632b004.png)

**Comment by PetyXbron** [comment]
A new version of the npm module `chalk` doesn't support the `require()` syntax import. (You probably have installed the v`5.0.1` - the latest one)
You need to **downgrade the chalk module to version: `4.1.2`**
Enter this command to your console for running your `minecraft-bot`:
```
npm install chalk@4.1.
```
