### ISSUE TITLE
Request functionality

### ISSUE THREAD

**Issue by Francesco99d** [PetyXbron/minecraft-bot#6]
Hi, I had a chance to try the bot and I would like to suggest some additions: it would be nice if you add a command to get the embedded message that updates automatically (compared to how it is now that a new message is sent every time the bot starts), suggest like: `/autoupdate`. 

Then it would be cool if there was the possibility to add the monitoring of multiple servers at the same time (maybe relying on the use of a database like mongodb) and in the end, to make the bot more complete, we would add a command to get the skins of a player. 
Thank you for your reply and I hope you can consider implementing these additions in the future, I wish you a good job :)

**Comment by PetyXbron** [comment]
Hello, thanks for the nice suggestion.
Did you know minecraft-bot project contains function, called **`statusCH`**? (config lines [here](https://github.com/PetyXbron/minecraft-bot/blob/cce9f407ed23256747d008efad5e8bf147cbddac/config.js#L31) and [here](https://github.com/PetyXbron/minecraft-bot/blob/cce9f407ed23256747d008efad5e8bf147cbddac/config.js#L56-L65))
You can't set it with Discord commands but it has (I think) a simple setup in the config, just allow the function, enter the guild and channel ID, and then you can restart the server. I could add a chat command setup, but I think it's not necessary now.

This project started as public source code for my own Discord bot for even commercial uses. I have a big, big history of moderating Minecraft servers so we hosted Discord servers for communication. "Own" Discord Minecraft server bot was cool to make our job easier and entertain, but also inform our players. I don't want to make one bot to power more Minecraft server that could hold more information. It could be simpler for running the bot for the servers, but I think this method gets users a lot of customizable config with interesting functions. Minecraft server admins should have options to operate this code so it's maybe more friendlier to have just one config without any complex commands.
Also you can find these bots already on the internet, like: [Minecraft Server Status](https://top.gg/bot/652726107535310859) and maybe [MC status](https://top.gg/bot/816747912888975362) too

**Comment by Francesco99d** [comment]
Hi, yes I've seen the configuration string `statusCH` and I've also activated it, that's why I was asking if it was possible to implement a command that would do the same function (maybe remembering the id of the message) so as to avoid creating a new message every time (since in my tests I had to restart the bot several times and it is inconvenient to always receive a new message to update the Server rather than update the one already present). 

On the fact of "supporting" only one server, I agree with you because in this way you avoid unnecessarily complicating the coding of the bot and you can better customize the bot according to the specific needs of the community.

P.s. I know the public bots you already mentioned and for this reason I was pushed to look for an open source one, just to see if I could replace the current [Minecraft Server Status](https://top.gg/bot/652726107535310859) (since lately it is having problems of inactivity). Anyway, thank you for your quick reply and for taking my suggestions into consideration, I wish you a good work and happy holidays :)

**Comment by Francesco99d** [comment]
Sorry for the insistence, but I saw that you closed the ticket without giving me any further answer, does this mean that you are not interested in implementing the suggestions? I would have expected an explanation (even a simple no would have been fine). In any case, I wish you a good day

**Comment by PetyXbron** [comment]
Hello @Francesco99d, do not worry I read your messages, I just want to limit opened issues number. As I said, I do not want to make a public bot for this. As you said, it's better for server moderators, because every server prefers other designs and I don't want to complicate things now.
If you delete the `json.sqlite` file in your project folder (before starting the bot without enabling `statusCH`, the file is missing - it's OK.) you will reset the memory of the message ID. It's a method how to remember the ID of a sent message to not send a new one again and again. If you deleted the old one, you just need to delete this file and after the new process start, it will send a new one.

**Comment by Francesco99d** [comment]
Oh ok, thanks for the tip.... Keep up the good work 💪

**Comment by PetyXbron** [comment]
Download the new update [v1.7.0](https://github.com/PetyXbron/minecraft-bot/releases/tag/1.7.0) or newer to support pure JSON data saving. You won't longer require `quick.db`.
