### ISSUE TITLE
maintenance integration

### ISSUE THREAD

**Issue by PetyXbron** [PetyXbron/minecraft-bot#8]
### Discussed in https://github.com/PetyXbron/minecraft-bot/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **Timong-craft** June  6, 2022</sup>
Can you impement the https://www.spigotmc.org/resources/maintenance-bungee-and-spigot-support.40699 plugin that if this is enabled the status is offline or do have I to ask it in `minecraft-server-util`?</div>

**Comment by Timong-craft** [comment]
And small Question, why is this Link in the index.js: https://www.planetminecraft.com/files/image/minecraft/project/2020/224/12627341-image_l.jpg
Becorse it doesn't work
![image](https://user-images.githubusercontent.com/77288029/173105258-e1895e34-a5d8-4cfe-a33f-0142aeaf1195.png)

**Comment by PetyXbron** [comment]
> And small Question, why is this Link in the index.js: https://www.planetminecraft.com/files/image/minecraft/project/2020/224/12627341-image_l.jpg Becorse it doesn't work ![image](https://user-images.githubusercontent.com/77288029/173105258-e1895e34-a5d8-4cfe-a33f-0142aeaf1195.png)

@Timong-craft Ugh... They deleted the file. 😐 Thanks for noticing. I think it was something like the default Minecraft world icon.
I will replace it in a new version with this one: 
![image](https://user-images.githubusercontent.com/35902119/173105998-c153dfe0-a579-426d-99d8-90f0ddcbbbd0.png)
(https://media.minecraftforum.net/attachments/300/619/636977108000120237.png)
It's just a fuse to get at least some image for embeds. If you have an "invalid" icon link in your config file it should replace it with some "default" one.

**Comment by Timong-craft** [comment]
ok, thx
