### ISSUE TITLE
Package Error

### ISSUE THREAD

**Issue by Timong-craft** [PetyXbron/minecraft-bot#9]
The better-sqlite3 package is broken, here is the working Package
[better-sqlite3.zip](https://github.com/PetyXbron/minecraft-bot/files/8883894/better-sqlite3.zip)

**Comment by PetyXbron** [comment]
Downgrading [quick.db](https://www.npmjs.com/package/quick.db) to [7.1.3](https://www.npmjs.com/package/quick.db/v/7.1.3) fixes the issue.
You can use this console command when the process is off: **`npm i quick.db@7.1.3 --save --save-exact`**
I do not have reason to update the package so we can leave it like this. Thank you for your info.

**Comment by PetyXbron** [comment]
With the new release [v1.7.0](https://github.com/PetyXbron/minecraft-bot/releases/tag/1.7.0) or newer no one shouldn't face this issue. Package [quick.db](https://www.npmjs.com/package/quick.db) is removed from the dependencies, newly using pure JSON data saving with [Node.js fs](https://nodejs.org/api/fs.html#file-system)
